#!/bin/bash
if [[ $# -ne 3 ]]; then 
    echo "usage: $0 <train-set-file> <test-set-file> <n|t>" 1>&2 # write error message to stderr (below)
    exit 0
fi

python_to_execute="Python/bayes.py"
python ${python_to_execute} $1 $2 $3